name: Observability CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure kubeconfig
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\.kube"

          @"
${{ secrets.KUBE_CONFIG }}
"@ | Out-File "$env:USERPROFILE\.kube\config" -Encoding ascii

          Write-Host "Current Context:"
          kubectl config current-context

      - name: Verify Runner
        shell: powershell
        run: |
          kubectl version --client
          kubectl get nodes

      - name: Validate Manifests
        shell: powershell
        run: |
          .\scripts\validate.ps1

      - name: Kubernetes Dry Run
        shell: powershell
        run: |
          kubectl apply --dry-run=client -f kubernetes

      - name: Deploy
        shell: powershell
        run: |
          kubectl apply -f kubernetes